name: CareTracker-demo

services:
  backend:
    container_name: caretracker-backend-demo
    image: caretracker-backend:demo
    build:
      context: ./backend
      dockerfile: Dockerfile.demo
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - APP_MAPY_API_KEY=${APP_MAPY_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    container_name: caretracker-frontend-demo
    image: caretracker-frontend:demo
    build:
      context: ./frontend
      dockerfile: Dockerfile.demo
    ports:
      - "3030:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    container_name: caretracker-db-demo
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_demo:/var/lib/postgresql/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend

volumes:
  pgdata_demo:
