-- Create daily_record table
CREATE TABLE "daily_record" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "date" DATE NOT NULL,
    "content" TEXT NOT NULL
);

-- Create individual_plan_content table with versioning support
CREATE TABLE "individual_plan_content" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "individual_plan_id" INT NOT NULL,
    "version_number" INT NOT NULL,
    "processed_date" DATE NOT NULL,
    "planned_update_date" DATE NOT NULL,
    "likes" TEXT,
    "dislikes" TEXT,
    "strengths" TEXT,
    "aspirations" TEXT,
    "life_path" TEXT,
    "additional_info" TEXT,
    "hygiene" TEXT,
    "self_care" TEXT,
    "mobility" TEXT,
    "diet" TEXT,
    "home_care" TEXT,
    "social_contact" TEXT,
    "activities" TEXT,
    "health" TEXT,
    "exercising_rights" TEXT,
    CONSTRAINT "unique_version_per_plan" UNIQUE ("individual_plan_id", "version_number")
);

-- Create join table for many-to-many relationship
CREATE TABLE "individual_plan_content_daily_record" (
    "individual_plan_content_id" INT NOT NULL,
    "daily_record_id" INT NOT NULL,
    PRIMARY KEY ("individual_plan_content_id", "daily_record_id")
);

-- Remove old content column and add reference to current version
ALTER TABLE "individual_plan"
DROP COLUMN "content";

ALTER TABLE "individual_plan"
ADD COLUMN "current_content_id" INT;

-- Add foreign key constraints
ALTER TABLE "individual_plan_content"
ADD CONSTRAINT "fk_individual_plan_content_plan"
FOREIGN KEY ("individual_plan_id")
REFERENCES "individual_plan"("id")
ON DELETE CASCADE;

ALTER TABLE "individual_plan"
ADD CONSTRAINT "fk_individual_plan_current_content"
FOREIGN KEY ("current_content_id")
REFERENCES "individual_plan_content"("id")
ON DELETE SET NULL;

ALTER TABLE "individual_plan_content_daily_record"
ADD CONSTRAINT "fk_ipc_daily_record_content"
FOREIGN KEY ("individual_plan_content_id")
REFERENCES "individual_plan_content"("id")
ON DELETE CASCADE;

ALTER TABLE "individual_plan_content_daily_record"
ADD CONSTRAINT "fk_ipc_daily_record_record"
FOREIGN KEY ("daily_record_id")
REFERENCES "daily_record"("id")
ON DELETE CASCADE;