CREATE TYPE "gender" AS ENUM (
  'MALE',
  'FEMALE'
);

CREATE TYPE "benefit_level" AS ENUM (
  'NONE',
  'ONE',
  'TWO',
  'THREE',
  'FOUR'
);

CREATE TYPE "employee_role" AS ENUM (
  'CAREGIVER',
  'COORDINATOR',
  'MANAGER'
);

CREATE TYPE "unit_type" AS ENUM (
  'HOUR',
  'OCCURRENCE',
  'KG',
  'KM'
);

CREATE TYPE "user_role" AS ENUM (
  'CAREGIVER',
  'COORDINATOR',
  'ADMIN',
  'CLIENT',
  'SUPERADMIN'
);

CREATE TABLE "client" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "gender" gender NOT NULL,
  "personal_number" int UNIQUE,
  "date_of_birth" date NOT NULL,
  "date_of_death" date,
  "email" varchar,
  "phone" varchar(16),
  "street" varchar NOT NULL,
  "city" varchar NOT NULL,
  "postal_code" char(6) NOT NULL,
  "legally_competent" boolean NOT NULL DEFAULT true,
  "benefits" benefit_level NOT NULL,
  "relatives_contact" text,
  "general_practitioner" text,
  "notes" text,
  "created" date NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "department_id" int NOT NULL,
  "caregiver_id" int NOT NULL
);

CREATE TABLE "picture" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "data" bytea,
  "client_id" int NOT NULL
);

CREATE TABLE "individual_plan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "client_id" int NOT NULL,
  "content" text
);

CREATE TABLE "client_task" (
  "client_id" int NOT NULL,
  "task_id" int NOT NULL,
  PRIMARY KEY ("client_id", "task_id")
);

CREATE TABLE "department" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "street" varchar NOT NULL,
  "city" varchar NOT NULL,
  "postal_code" char(6) NOT NULL,
  "coordinator_id" int,
  "organization_id" int NOT NULL
);

CREATE TABLE "organization" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "manager_id" int
);

CREATE TABLE "employee" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "role" employee_role NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "department_id" int NOT NULL
);

CREATE TABLE "performed_task" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "client_id" int NOT NULL,
  "task_id" int NOT NULL,
  "date" date NOT NULL,
  "unit_count" int NOT NULL,
  "notes" text
);

CREATE TABLE "caregiver_performed_task" (
  "caregiver_id" int NOT NULL,
  "performed_task_id" int NOT NULL,
  PRIMARY KEY ("caregiver_id", "performed_task_id")
);

CREATE TABLE "task" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "task_name" varchar NOT NULL,
  "unit_price" int NOT NULL,
  "unit_type" unit_type NOT NULL DEFAULT 'HOUR',
  "double_meeting" boolean NOT NULL DEFAULT false
);

CREATE TABLE "app_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar,
  "role" user_role NOT NULL,
  "activation_token" varchar,
  "token_expiry" timestamp,
  "active" boolean NOT NULL DEFAULT true,
  "employee_id" int,
  "client_id" int
);

ALTER TABLE "client" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id");

ALTER TABLE "picture" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "individual_plan" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "client_task" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "client_task" ADD FOREIGN KEY ("task_id") REFERENCES "task" ("id");

ALTER TABLE "department" ADD FOREIGN KEY ("coordinator_id") REFERENCES "employee" ("id");

ALTER TABLE "department" ADD FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");

ALTER TABLE "organization" ADD FOREIGN KEY ("manager_id") REFERENCES "employee" ("id");

ALTER TABLE "employee" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id");

ALTER TABLE "caregiver_performed_task" ADD FOREIGN KEY ("caregiver_id") REFERENCES "employee" ("id");

ALTER TABLE "caregiver_performed_task" ADD FOREIGN KEY ("performed_task_id") REFERENCES "performed_task" ("id");

ALTER TABLE "app_user" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("id");

ALTER TABLE "app_user" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "client" ADD FOREIGN KEY ("caregiver_id") REFERENCES "employee" ("id") ON DELETE RESTRICT;

ALTER TABLE "performed_task" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id") ON DELETE RESTRICT;

ALTER TABLE "performed_task" ADD FOREIGN KEY ("task_id") REFERENCES "task" ("id") ON DELETE RESTRICT;
