<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 sp1 (x64) (http://www.altova.com) by ﻿Administrator (OKsystem Ltd.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://portal.mpsv.cz/soc/ssl/poskyt/pgm_info/rozhrani" targetNamespace="http://portal.mpsv.cz/soc/ssl/poskyt/pgm_info/rozhrani" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="VykazyImport">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Hlavicka"/>
				<xs:choice>
					<xs:element ref="KartaZamestnance" maxOccurs="unbounded"/>
					<xs:element ref="KartyUzivateluSluzby" maxOccurs="unbounded"/>
					<xs:element ref="CinnostiAnonymUzivatelum" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="KartaZamestnance">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ZakladniInformace">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="IdentifikatorZamestnance" type="IdentifikatorTyp">
								<xs:annotation>
									<xs:documentation>Identifikátor zaměstnance, unikátní v rámci celého podávaného výkazu poskytovatele, tedy přes všechny služby, za které podává výkaz. Identifikátor vytváří aplikace generující importní soubor.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element ref="Pohlavi" minOccurs="0"/>
							<xs:element ref="RokNarozeni" minOccurs="0"/>
							<xs:element name="KodDosazeneVzdelani" type="CiselnikBaseTyp" minOccurs="0"/>
							<xs:element name="PocetLetPraxe" type="PocetLetTyp" minOccurs="0"/>
							<xs:element name="PocetLetPracPomeruVOrg" type="PocetLetTyp" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Počet let pracovního poměru v organizaci</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PracovniPoziceSluzba" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="IdentifikatorSluzby"/>
							<xs:element name="KodPracovniPozice" type="CiselnikBaseTyp"/>
							<xs:element name="TypPracovnihoPomeru" type="PracovniPomerTyp"/>
							<xs:element name="Uvazek" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minExclusive value="0"/>
										<xs:maxInclusive value="1"/>
										<xs:fractionDigits value="4"/>
										<xs:totalDigits value="5"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RozsahPrace" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:short">
										<xs:maxInclusive value="300"/>
										<xs:minExclusive value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Období výkonu pracovního poměru</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="IdentifikatorPracSmlouvy" type="IdentifikatorTyp" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Nepovinný identifikátor unikátní alespoň v rámci zaměstnance a sociální služby</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Vzdelavani" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="KodVzdelavani" type="CiselnikBaseTyp"/>
							<xs:element name="PocetHodin" type="PocetTyp" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DelkaPracPomeru" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="IdentifikatorSluzby"/>
							<xs:element name="PocetLet" type="PocetLetTyp">
								<xs:annotation>
									<xs:documentation>Počet let pracovního poměru v sociální službě</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="KartyUzivateluSluzby">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IdentifikatorSluzby"/>
				<xs:element name="KartaUzivatele" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Uzivatel">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="IdentifikatorUzivatele" type="IdentifikatorTyp">
											<xs:annotation>
												<xs:documentation>Identifikátor uživatele sociální služby, unikátní alespoň v rámci sociální služby a roku výkazu. Identifikátor vytváří aplikace generující importní soubor.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="Pohlavi" minOccurs="0"/>
										<xs:element ref="RokNarozeni" minOccurs="0"/>
										<xs:element name="KodCiloveSkupiny" type="CiselnikBaseTyp" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:choice>
								<xs:element ref="OsobniAsistence" minOccurs="0"/>
								<xs:element ref="PecovatelskaSluzba" minOccurs="0"/>
								<xs:element ref="TisnovaPece" minOccurs="0"/>
								<xs:element ref="PruvodPredcitSluzby" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Průvodcovské a předčitatelské služby</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element ref="PodporaSamostBydleni" minOccurs="0"/>
								<xs:element ref="OdlehcovaciSluzby" minOccurs="0"/>
								<xs:element ref="CentraDennichSluzeb" minOccurs="0"/>
								<xs:element ref="DenniStacionar" minOccurs="0"/>
								<xs:element ref="TydenniStacionare" minOccurs="0"/>
								<xs:element ref="DomovyProOsZdrPostizeni" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Domovy pro osoby se zdravotním postižením</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element ref="DomovyProSeniory" minOccurs="0"/>
								<xs:element ref="DomovySeZvlRezimem" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Domovy se zvláštním režimem</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element ref="ChraneneBydleni" minOccurs="0"/>
								<xs:element ref="SocSlPoskytZdrZarizUP" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Sociální služby poskytované ve zdrav. zařízeních ústavní péče</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element ref="AzyloveDomy" minOccurs="0"/>
								<xs:element ref="DomyNaPulCesty" minOccurs="0"/>
								<xs:element ref="SluzbyNaslednePece" minOccurs="0"/>
								<xs:element ref="SocialneTerapeutDilny" minOccurs="0"/>
								<xs:element ref="TerapeutickeKomunity" minOccurs="0"/>
							</xs:choice>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="FakultativniCinnosti" minOccurs="0"/>
				<xs:element name="CinnostiSluzby" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Činnosti vykazované za službu</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice>
							<xs:element name="DomyNaPulCesty" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
										<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
										<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="21"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="SluzbyNaslednePece" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
										<xs:element ref="SocTerapVedoucKAbstinenciProc" minOccurs="0"/>
										<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="27"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="SocialneTerapeutDilny" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="NacvikDovedKSocZaclProc" minOccurs="0"/>
										<xs:element ref="PodporaZaklPracNavykDovedProc" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="30"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="TerapeutickeKomunity" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
										<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
										<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="31"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CinnostiAnonymUzivatelum">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IdentifikatorSluzby"/>
				<xs:choice>
					<xs:element ref="OdborneSocPoradenstvi" minOccurs="0"/>
					<xs:element ref="RanaPece" minOccurs="0"/>
					<xs:element ref="TelefKrizovaPomoc" minOccurs="0"/>
					<xs:element ref="TlumocnickeSluzby" minOccurs="0"/>
					<xs:element ref="KontaktniCentra" minOccurs="0"/>
					<xs:element ref="KrizovaPomoc" minOccurs="0"/>
					<xs:element ref="NizkoprahDenniCentra" minOccurs="0"/>
					<xs:element ref="NizkoPrahZarDetiMladez" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Nízkoprahová zařízení pro děti a mládež</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element ref="Nocleharny" minOccurs="0"/>
					<xs:element ref="SocAktivSlProRodinySDetmi" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Sociálně aktivizační služby pro rodiny s dětmi</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element ref="SocAktivSlProSenioryAOZP" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Sociálně aktivizační služby pro seniory a osoby se zdravotním postižením</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element ref="TerenniProgramy" minOccurs="0"/>
					<xs:element ref="SocialniRehabilitace" minOccurs="0"/>
					<xs:element ref="IntervencniCentra" minOccurs="0"/>
					<xs:element ref="CentrumDusevnihoZdravi" minOccurs="0"/>
				</xs:choice>
				<xs:element ref="FakultativniCinnosti" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IdentifikatorSluzby">
		<xs:annotation>
			<xs:documentation>Identifikátor, který je uveden na rozhodnutí  o registraci soc. služby nebo na sdělení o zavedení soc. služby do registru</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:unsignedLong">
				<xs:minExclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="RokNarozeni" type="CisloRokTyp"/>
	<xs:element name="Pohlavi" type="PohlaviTyp"/>
	<xs:element name="Hlavicka">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="VerzeImportu" type="xs:int">
					<xs:annotation>
						<xs:documentation>Číslo platné verze importu</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="RokVykazu" type="CisloRokTyp">
					<xs:annotation>
						<xs:documentation>Rok, za který se zpracovává výkaz sociálních služeb</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="DatumACasVytvoreni" type="xs:dateTime">
					<xs:annotation>
						<xs:documentation>Datum a čas vytvoření importního souboru</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Popis" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Popis sloužící obsluze k identifikaci importního souboru</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="254"/>
							<xs:whiteSpace value="collapse"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatumOd" type="xs:date"/>
	<xs:element name="DatumDo" type="xs:date"/>
	<xs:element name="CelkovyPocetHodin" type="PocetTypDesetiny"/>
	<xs:element name="PocetSetkani" type="PocetTyp"/>
	<xs:element name="Obdobi">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatumOd"/>
				<xs:element ref="DatumDo" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PoskytStravyPomocZajistStravy" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Poskytnutí stravy / pomoc při zajištění stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="VelkeNakupy" type="PocetTyp"/>
	<xs:element name="PraniZehleniDrobneOpravy" type="PocetTypDesetiny">
		<xs:annotation>
			<xs:documentation>Praní a žehlení prádla, drobné opravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ZprostredKontaktSpolProstrAN" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Zprostředkování kontaktu se spol. prostř.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocBeznychZalezitost" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při vyřizování běžných záležitostí</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocKomunPriUplPravZajmu" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při komunikaci při uplatňování práv a zájmů</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PredcitaniJinyZpZprostredInfo" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Předčítání / jiný způsob zprostředkování informace</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocUplPravZajmuAJAN" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při uplatňování práv, zájmů aj.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocUplPravZajmuAJProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při uplatňování práv, zájmů aj.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="SocialneTerapeutCinnostAN" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Sociálně terapeutické činnosti</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="SocialneTerapeutCinnostProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Sociálně terapeutické činnosti</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PoskytNeprDistHlasElKom" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Poskytování nepřetržité dist. hlas. a el. komunikace</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ZprostredZdravZachSlPolAJ" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Zprostředkování zdrav. záchr. služby, policie aj.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="VychVzdelAktCinnosti" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Výchovné, vzděl. a akt. činnosti</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocUkonPeceVlOsoba" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při úkonech péče o vlastní osobu</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocOsHygienPoskPodminek" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při os. hygieně / poskytnutí podmínek</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PoskytStravy" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Poskytnutí stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocPriZajistStravy" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při zajištění stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="CelkovyPocetDni" type="PocetTypDesetiny"/>
	<xs:element name="PoskytZdravPece" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Poskytování zdravotní péče</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="AktivizacniCinnost" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Aktivizační činnosti</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocSChodemDoma" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc s chodem domácnosti</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocPripravaStravy" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Pomoc s přípravou stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ZajisteniStravy" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Zajištění stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="VyuzitiPodmProPripravStravy" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Využití podmínek pro přípravu stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ZajisteniPoskytStravy" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Zajištění / poskytnutí stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ZprostredKontaktSpolProstrProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Zprostředkování kontaktu se spol. prostř.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="SocTerapVedoucKAbstinenciProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Soc. terap. č. vedoucí k abstinenci atd.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="NacvikDovedKSocZaclProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Nácvik dovedností k soc. začleňování</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PodporaZaklPracNavykDovedProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Podpora zákl. prac. návyků a doved</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PomocOsHygienPoskPodmPocet" type="PocetTyp">
		<xs:annotation>
			<xs:documentation>Pomoc při os. hygieně / poskytnutí podmínek</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="VyuziPodmProPriprStraPomPripr" type="AnoNeTyp">
		<xs:annotation>
			<xs:documentation>Využití podm. pro přípravu stravy / pomoc s přípravou</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="StupenZavislosti" type="StupenZavislostiTyp"/>
	<xs:element name="TrvaleBydlisteVZarizeni" type="AnoNeTyp"/>
	<xs:element name="KodOkresuBydlistePred">
		<xs:annotation>
			<xs:documentation>Okres bydliště před počátkem poskytování služby</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minExclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PocetOsobZijicichSUzivatelem" type="PocetNezapornyTyp">
		<xs:annotation>
			<xs:documentation>Počet osob žijících s uživatelem</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="IntervenceVZajmuKlienta" type="PocetTyp"/>
	<xs:element name="PocetSetkaniDo15min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniDo30min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniDo60min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniDo90min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniDo120min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniNad120min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniDo150min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniDo180min" type="PocetTyp"/>
	<xs:element name="PocetSetkaniNad180min" type="PocetTyp"/>
	<xs:element name="VychVzdelAktCinnostiProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Výchovné, vzděl. a akt. činnosti</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PoskytPomOsHygienaProc" type="ProcentaTyp">
		<xs:annotation>
			<xs:documentation>Poskytnutí podmínek pro os. hygienu</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PocetSetkaniNad60min" type="PocetTyp"/>
	<xs:element name="PocUzivPoskytStrava" type="PocetTyp">
		<xs:annotation>
			<xs:documentation>Počet uživatelů, kterým byla poskytnuta strava</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PocUzivZajistPomocZajistStravy" type="PocetTyp">
		<xs:annotation>
			<xs:documentation>Počet uživatelů, kterému byla zajištěna pomoc při zajištění stravy</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PocSkutVyuzLuzkodnu" type="PocetTyp">
		<xs:annotation>
			<xs:documentation>Počet skutečně využitých lůžkodnů</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="MaxPocVyuzLuzkodnu" type="PocetTyp">
		<xs:annotation>
			<xs:documentation>Maximální počet využitelných lůžkodnů</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PocPoskytJidel" type="PocetTyp">
		<xs:annotation>
			<xs:documentation>Počet poskytnutých jídel</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PoskytPrenocovani" type="PocetTyp">
		<xs:annotation>
			<xs:documentation>Poskytnutí přenocování</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="SocTerapCinnKrizInterADalsi" type="ProcentaTyp"/>
	<xs:element name="FakultativniCinnosti">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="KodFakultativniCinnosti" type="CiselnikBaseTyp" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="JinaFakultCinnost" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:whiteSpace value="preserve"/>
							<xs:maxLength value="2000"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="PruvodPredcitSluzbyATSkupina">
		<xs:sequence>
			<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
			<xs:element ref="PocetSetkani" minOccurs="0"/>
			<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
			<xs:element ref="PomocBeznychZalezitost" minOccurs="0"/>
			<xs:element ref="PomocKomunPriUplPravZajmu" minOccurs="0"/>
			<xs:element ref="PredcitaniJinyZpZprostredInfo" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PecovatelskaSluzbaATSkupina">
		<xs:sequence>
			<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
			<xs:element ref="PocetSetkani" minOccurs="0"/>
			<xs:element ref="PoskytStravyPomocZajistStravy" minOccurs="0"/>
			<xs:element ref="VelkeNakupy" minOccurs="0"/>
			<xs:element ref="PraniZehleniDrobneOpravy" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="OdlehcovaciSluzbaPATSkupina">
		<xs:sequence>
			<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
			<xs:element ref="PocetSetkani" minOccurs="0"/>
			<xs:element ref="PomocUkonPeceVlOsoba" minOccurs="0"/>
			<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
			<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
			<xs:element ref="VychVzdelAktCinnosti" minOccurs="0"/>
			<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
			<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
			<xs:element ref="PoskytStravy" minOccurs="0"/>
			<xs:element ref="PomocPriZajistStravy" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PoctySetkaniSkupina">
		<xs:sequence>
			<xs:element ref="PocetSetkaniDo15min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo90min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo120min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniNad120min" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="OdborneSocPoradATSkupina">
		<xs:sequence>
			<xs:group ref="PoctySetkaniSkupina"/>
			<xs:element ref="IntervenceVZajmuKlienta" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="RanaPeceATSkupina">
		<xs:sequence>
			<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo90min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo120min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo150min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo180min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniNad180min" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="KontaktniCentraATSkupina">
		<xs:sequence>
			<xs:element ref="PocetSetkaniDo15min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo90min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo120min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo150min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo180min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniNad180min" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="KrizovaPomocPATSkupina">
		<xs:sequence>
			<xs:element ref="PocetSetkaniDo15min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniNad60min" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="NizkoprahDenniCentraTASKupina">
		<xs:sequence>
			<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
			<xs:element ref="PocetSetkaniNad60min" minOccurs="0"/>
			<xs:element ref="PomocOsHygienPoskPodmPocet" minOccurs="0"/>
			<xs:element ref="PocUzivPoskytStrava" minOccurs="0"/>
			<xs:element ref="PocPoskytJidel" minOccurs="0"/>
			<xs:element ref="PocUzivZajistPomocZajistStravy" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="CisloRokTyp">
		<xs:restriction base="xs:unsignedShort">
			<xs:pattern value="[1-9][0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AnoNeTyp">
		<xs:restriction base="xs:string">
			<xs:enumeration value="A"/>
			<xs:enumeration value="N"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PohlaviTyp">
		<xs:restriction base="xs:string">
			<xs:enumeration value="M"/>
			<xs:enumeration value="F"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CiselnikBaseTyp">
		<xs:restriction base="xs:unsignedShort">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ProcentaTyp">
		<xs:restriction base="xs:unsignedByte">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PocetTyp">
		<xs:restriction base="xs:unsignedInt">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PocetNezapornyTyp">
		<xs:restriction base="xs:unsignedInt">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PocetTypDesetiny">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PocetLetTyp">
		<xs:restriction base="xs:unsignedShort">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PracovniPomerTyp">
		<xs:restriction base="CiselnikBaseTyp">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>dohoda o provedení činnosti</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>dohoda o provedení práce</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>pracovní smlouva</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StupenZavislostiTyp">
		<xs:restriction base="CiselnikBaseTyp">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>lehká závislost</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>středně těžká závislost</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>těžká závislost</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>úplná závislost</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IdentifikatorTyp">
		<xs:restriction base="xs:string">
			<xs:maxLength value="60"/>
			<xs:whiteSpace value="collapse"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FormySluzbyTyp">
		<xs:restriction base="CiselnikBaseTyp">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Pobytová</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Ambulantní</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Terénní</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="OdborneSocPoradenstvi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="OdborneSocPoradATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="OdborneSocPoradATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
				<xs:element name="PoradenOblOrientSocSystem" type="AnoNeTyp" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Poradenství v oblasti orientace v sociálních systémech</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PoradenOblPrava" type="AnoNeTyp" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Poradenství v oblasti práva</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PoradenOblPsychologie" type="AnoNeTyp" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Poradenství v oblasti psychologie</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PoradenOblVzdelani" type="AnoNeTyp" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Poradenství v oblasti vzdělání</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PujcovaniKompenzPomucek" type="PocetTyp" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="1"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="RanaPece">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="RanaPeceATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="RanaPeceATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
				<xs:element ref="VychVzdelAktCinnostiProc" minOccurs="0"/>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="17"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TelefKrizovaPomoc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Terenni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:sequence>
									<xs:element name="PocetHovoruDo5min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo10min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo15min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo20min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo25min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo30min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo35min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo40min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo45min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo50min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo55min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruDo60min" type="PocetTyp" minOccurs="0"/>
									<xs:element name="PocetHovoruNad60min" type="PocetTyp" minOccurs="0"/>
									<xs:element ref="IntervenceVZajmuKlienta" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="18"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TlumocnickeSluzby">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="19"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="KontaktniCentra">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="KontaktniCentraATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="KontaktniCentraATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
				<xs:element ref="PoskytPomOsHygienaProc" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="22"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="KrizovaPomoc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="KrizovaPomocPATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="KrizovaPomocPATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pobytova" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:group ref="KrizovaPomocPATSkupina"/>
									<xs:element ref="PocUzivPoskytStrava" minOccurs="0"/>
									<xs:element ref="PocUzivZajistPomocZajistStravy" minOccurs="0"/>
									<xs:element ref="PocSkutVyuzLuzkodnu" minOccurs="0"/>
									<xs:element ref="MaxPocVyuzLuzkodnu" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="23"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="NizkoprahDenniCentra">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="NizkoprahDenniCentraTASKupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="NizkoprahDenniCentraTASKupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="24"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="NizkoPrahZarDetiMladez">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniNad60min" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
				<xs:element ref="VychVzdelAktCinnostiProc" minOccurs="0"/>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="25"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Nocleharny">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element ref="PomocOsHygienPoskPodmPocet" minOccurs="0"/>
									<xs:element ref="PoskytPrenocovani" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="26"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SocAktivSlProRodinySDetmi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
				<xs:element ref="VychVzdelAktCinnostiProc" minOccurs="0"/>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="28"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SocAktivSlProSenioryAOZP">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="29"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TerenniProgramy">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Terenni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:sequence>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="32"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SocialniRehabilitace">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element ref="PocetSetkaniDo15min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniNad60min" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:sequence>
									<xs:element ref="PocetSetkaniDo15min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniNad60min" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pobytova" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="PomocOsHygienPoskPodmPocet" minOccurs="0"/>
									<xs:element ref="PocUzivPoskytStrava" minOccurs="0"/>
									<xs:element ref="PocSkutVyuzLuzkodnu" minOccurs="0"/>
									<xs:element ref="MaxPocVyuzLuzkodnu" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
				<xs:element ref="VychVzdelAktCinnostiProc" minOccurs="0"/>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="NacvikDovedKSocZaclProc" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="33"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="IntervencniCentra">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pobytova" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="PocUzivPoskytStrava" minOccurs="0"/>
									<xs:element ref="PocUzivZajistPomocZajistStravy" minOccurs="0"/>
									<xs:element ref="PocSkutVyuzLuzkodnu" minOccurs="0"/>
									<xs:element ref="MaxPocVyuzLuzkodnu" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="SocTerapCinnKrizInterADalsi" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Soc. terap. č.: kriz. intervence a další  (sociálně terapeutické činnosti: krizová intervence a další socioterapeutické činnosti atd.)</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="34"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CentrumDusevnihoZdravi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element ref="PocetSetkaniDo15min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniNad60min" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:sequence>
									<xs:element ref="PocetSetkaniDo15min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo30min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniDo60min" minOccurs="0"/>
									<xs:element ref="PocetSetkaniNad60min" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="ZprostredKontaktSpolProstrProc" minOccurs="0"/>
				<xs:element ref="VychVzdelAktCinnostiProc" minOccurs="0"/>
				<xs:element ref="PomocUplPravZajmuAJProc" minOccurs="0"/>
				<xs:element ref="NacvikDovedKSocZaclProc" minOccurs="0"/>
				<xs:element ref="SocialneTerapeutCinnostProc" minOccurs="0"/>				
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="35"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="OsobniAsistence">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Terenni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:sequence>
									<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
									<xs:element ref="PocetSetkani" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="3"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PecovatelskaSluzba">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="PecovatelskaSluzbaATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="PecovatelskaSluzbaATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PoskytSluzbyBezUhrady" type="AnoNeTyp" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="4"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TisnovaPece">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Terenni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:sequence>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PoskytNeprDistHlasElKom" minOccurs="0"/>
									<xs:element ref="ZprostredZdravZachSlPolAJ" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování služby</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="5"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PruvodPredcitSluzby">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="PruvodPredcitSluzbyATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="PruvodPredcitSluzbyATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="6"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DomovyProOsZdrPostizeni">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="TrvaleBydlisteVZarizeni" minOccurs="0"/>
									<xs:choice minOccurs="0">
										<xs:element ref="BydlisteZahranici"/>
										<xs:element ref="KodOkresuBydlistePred"/>
									</xs:choice>
									<xs:element ref="PomocUkonPeceVlOsoba" minOccurs="0"/>
									<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="VychVzdelAktCinnosti" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PoskytZdravPece" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="StupenZavislosti" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="12"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TydenniStacionare">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="PomocUkonPeceVlOsoba" minOccurs="0"/>
									<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="VychVzdelAktCinnosti" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PoskytZdravPece" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="StupenZavislosti" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="11"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DenniStacionar">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element ref="CelkovyPocetDni" minOccurs="0"/>
									<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
									<xs:element ref="PomocUkonPeceVlOsoba" minOccurs="0"/>
									<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="VychVzdelAktCinnosti" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PoskytStravy" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="10"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CentraDennichSluzeb">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element ref="CelkovyPocetDni" minOccurs="0"/>
									<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
									<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="VychVzdelAktCinnosti" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PoskytStravy" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="9"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="OdlehcovaciSluzby">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element ref="CelkovyPocetDni" minOccurs="0"/>
									<xs:group ref="OdlehcovaciSluzbaPATSkupina"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Terenni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:group ref="OdlehcovaciSluzbaPATSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pobytova" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:group ref="OdlehcovaciSluzbaPATSkupina"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="8"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PodporaSamostBydleni">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Terenni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyTerenniTyp">
								<xs:sequence>
									<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
									<xs:element ref="PocetSetkani" minOccurs="0"/>
									<xs:element ref="PomocSChodemDoma" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="VychVzdelAktCinnosti" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování služby</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="7"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DomovyProSeniory">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="TrvaleBydlisteVZarizeni" minOccurs="0"/>
									<xs:choice minOccurs="0">
										<xs:element ref="BydlisteZahranici"/>
										<xs:element ref="KodOkresuBydlistePred"/>
									</xs:choice>
									<xs:element ref="PomocUkonPeceVlOsoba" minOccurs="0"/>
									<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="AktivizacniCinnost" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PoskytZdravPece" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="StupenZavislosti" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="13"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DomovySeZvlRezimem">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="TrvaleBydlisteVZarizeni" minOccurs="0"/>
									<xs:choice minOccurs="0">
										<xs:element ref="BydlisteZahranici"/>
										<xs:element ref="KodOkresuBydlistePred"/>
									</xs:choice>
									<xs:element ref="PomocUkonPeceVlOsoba" minOccurs="0"/>
									<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="AktivizacniCinnost" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PoskytZdravPece" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="StupenZavislosti" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="14"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ChraneneBydleni">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="CelkovyPocetHodin" minOccurs="0"/>
									<xs:element ref="PocetSetkani" minOccurs="0"/>
									<xs:element ref="PomocSChodemDoma" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="VychVzdelAktCinnosti" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="PomocPripravaStravy" minOccurs="0"/>
									<xs:element ref="ZajisteniStravy" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="15"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SocSlPoskytZdrZarizUP">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="PomocUkonPeceVlOsoba" minOccurs="0"/>
									<xs:element ref="PomocOsHygienPoskPodminek" minOccurs="0"/>
									<xs:element ref="ZprostredKontaktSpolProstrAN" minOccurs="0"/>
									<xs:element ref="PomocUplPravZajmuAJAN" minOccurs="0"/>
									<xs:element ref="SocialneTerapeutCinnostAN" minOccurs="0"/>
									<xs:element ref="AktivizacniCinnost" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="StupenZavislosti" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="16"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="AzyloveDomy">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="PocetOsobZijicichSUzivatelem" minOccurs="0"/>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="VyuzitiPodmProPripravStravy" minOccurs="0"/>
									<xs:element ref="ZajisteniPoskytStravy" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" use="required" fixed="20"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DomyNaPulCesty">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:element ref="PocetOsobZijicichSUzivatelem" minOccurs="0"/>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="21"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SluzbyNaslednePece">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:group ref="PoctySetkaniSkupina"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pobytova" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="ZajisteniPoskytStravy" minOccurs="0"/>
									<xs:element ref="VyuzitiPodmProPripravStravy" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="27"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SocialneTerapeutDilny">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ambulantni">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyAmbulantniTyp">
								<xs:sequence>
									<xs:element name="PocetDniVeSluzbe" type="PocetTypDesetiny" minOccurs="0"/>
									<xs:element name="PocetHodinVeSluzbe" type="PocetTypDesetiny" minOccurs="0"/>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="PomocOsHygienPoskPodmPocet" minOccurs="0"/>
									<xs:element ref="PomocPriZajistStravy" minOccurs="0"/>
									<xs:element ref="PoskytStravy" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="30"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TerapeutickeKomunity">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pobytova">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FormaSluzbyPobytovaTyp">
								<xs:sequence>
									<xs:group ref="PoctySetkaniSkupina"/>
									<xs:element ref="ZajisteniPoskytStravy" minOccurs="0"/>
									<xs:element ref="VyuziPodmProPriprStraPomPripr" minOccurs="0"/>
									<xs:element ref="Obdobi" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>Období poskytování ubytování</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="kodDruhuSluzby" type="CiselnikBaseTyp" use="required" fixed="31"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="FormaSluzbyTerenniTyp">
		<xs:attribute name="kodFormy" type="FormySluzbyTyp" use="required" fixed="3"/>
	</xs:complexType>
	<xs:complexType name="FormaSluzbyPobytovaTyp">
		<xs:attribute name="kodFormy" type="FormySluzbyTyp" use="required" fixed="1"/>
	</xs:complexType>
	<xs:complexType name="FormaSluzbyAmbulantniTyp">
		<xs:attribute name="kodFormy" type="FormySluzbyTyp" use="required" fixed="2"/>
	</xs:complexType>
	<xs:element name="BydlisteZahranici" type="AnoNeTyp"/>
</xs:schema>
