name: CareTracker-DB

services:
  db:
    container_name: caretracker-db-dev
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: caretracker
      POSTGRES_PASSWORD: caretracker
      POSTGRES_DB: caretracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  pgadmin:
    container_name: caretracker-pgadmin-dev
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@caretracker.cz
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin

volumes:
  pgdata_dev:
  pgadmin_data_dev:
