spring.application.name=CareTracker

#spring.datasource.url=jdbc:postgresql://localhost:5432/caretracker
#spring.datasource.username=caretracker_user
#spring.datasource.password=secret
#spring.jpa.hibernate.ddl-auto=update